### ISSUE TITLE
二级评论数量错误且保存失败

### ISSUE THREAD

**Issue by sjwu23** [alphaply/DouyinComments#16]
大佬您好，在爬二级评论的时候出现了如下报错，显示的数量严重不对而且存不下来，求解答
![Uploading 20241120014013.png…]()

**Comment by sjwu23** [comment]
图好像显示不出来，这是报错显示：
D:\神说工作日\pypro\DouyinComments-master\venv\Scripts\python.exe D:\神说工作日\pypro\DouyinComments-master\main.py 
Enter the aweme_id: 7438564015162346764
Fetching comments: 491comment [00:25, 19.57comment/s]
Found 491 comments.
Fetching replies: 100%|██████████| 491/491 [00:59<00:00,  8.19comment/s]
Found 7828 replies
Found 8319 in totals
Traceback (most recent call last):
  File "D:\神说工作日\pypro\DouyinComments-master\main.py", line 157, in <module>
    asyncio.run(main())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\神说工作日\pypro\DouyinComments-master\main.py", line 151, in main
    all_replies = process_replies(all_replies, all_comments_)
  File "D:\神说工作日\pypro\DouyinComments-master\main.py", line 110, in process_replies
    data = [
  File "D:\神说工作日\pypro\DouyinComments-master\main.py", line 127, in <listcomp>
    "回复给谁": comments.loc[comments['评论ID'] == c["reply_id"], '用户昵称'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

进程已结束,退出代码1

**Comment by sjwu23** [comment]
自己调整好了，还是感谢大佬！

**Comment by liliospp** [comment]
> 自己调整好了，还是感谢大佬！
请问uu是咋调整的？我也出现了一样的报错🙏

**Comment by LilyChien** [comment]
礼貌问如何解决，我现在也遇到了相同的问题，二级评论的保存不下来

**Comment by liliospp** [comment]
你好，今晚看邮箱才发现这条邮件，不知你解决了嘛～我当时就是重新按照首页的步骤安装了一下，然后再实验就成功啦。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年03月06日 08:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alphaply/DouyinComments] 二级评论数量错误且保存失败 (Issue #16) |

礼貌问如何解决，我现在也遇到了相同的问题，二级评论的保存不下来

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

LilyChien left a comment (alphaply/DouyinComments#16)

礼貌问如何解决，我现在也遇到了相同的问题，二级评论的保存不下来
